### ISSUE TITLE
toAnimate设置为NO的问题

### ISSUE THREAD

**Issue by bluesea** [wangmchn/YKPageView#1]
toAnimate设置为NO之后，点击Item，cell不重新创建。请问如何处理呢

**Comment by wangmchn** [comment]
你好，由于cell是复用的，所以如果设置toAnimate为NO的话，可能无法体现出cell内部内容的变化。
建议在- pageView：cellForRowAtIndex代理方法中对cell内部视图进行改变。
或者关注我的另一个由Controller做为cell的项目WMPageController，这个应该会更好用。

发自我的 iPhone
